### ISSUE TITLE
not able to configure kube_ping with jgroups

### ISSUE THREAD

**Issue by navdeepbansal** [jgroups-extras/jgroups-kubernetes#140]
Project is not able to identify KUBE_PING, i have added jgroups-kubernetes dependecy, still it says 'KUBE_PING' not loaded

**Comment by rhusar** [comment]
You also need to add the protocol to your JGroups stack.

**Comment by navdeepbansal** [comment]
protocol i have added with TCP in jgroups-config.xml file
<TCP ...... />
<org.jgroups.protocols.kubernetes.KUBE_PING port_range..... />


this is how i have done it. or is some other protocol i need to add ?

**Comment by rhusar** [comment]
@navdeepbansal have you had a chance to look into this? Can we close this now?

**Comment by navdeepbansal** [comment]
yes @rhusar, it can be closed.
