### ISSUE TITLE
Rename primary branch to 'main'

### ISSUE THREAD

**Issue by rhusar** [jgroups-extras/jgroups-kubernetes#152]
https://www.redhat.com/en/blog/making-open-source-more-inclusive-eradicating-problematic-language

**Comment by belaban** [comment]
If you agree with the above statement (I don't, `master` is not a discriminating word IMO), you can go ahead and make that change. You've kind of become the owner of jgroups-kuberenetes anyway... :-)

**Comment by rhusar** [comment]
Yes the issues is intended for myself :)

**Comment by rhusar** [comment]
Done now  – https://github.com/jgroups-extras/jgroups-kubernetes/pull/153 – closed.
