### ISSUE TITLE
Unable to load protocol

### ISSUE THREAD

**Issue by stief510** [jgroups-extras/jgroups-kubernetes#163]
I have added the protocol to my jgroups file but I am getting an error

```
        <org.jgroups.protocols.kubernetes.KUBE_PING
                port_range="0"
                namespace="d187612"
        />
```

Caused by: java.lang.Exception: JGRP000002: unable to load protocol org.jgroups.protocols.kubernetes.KUBE_PING (either with relative - org.jgroups.protocols.kubernetes.KUBE_PING - or absolute - org.jgroups.protocols.org.jgroups.protocols.kubernetes.KUBE_PING - class name)

**Comment by rhusar** [comment]
I think this is a message you get when you are missing a jar (the one that this project builds) on the class path. 

You can either (1) add dependency to your pom, (2) or download directly from maven https://repository.jboss.org/nexus/content/repositories/releases/org/jgroups/kubernetes/jgroups-kubernetes/ or (3) build from this repo/download sources.

**Comment by rhusar** [comment]
Looks like the readme of this project can do a better job explaining installation instructions..

**Comment by belaban** [comment]
Try `kubernetes.KUBE_PING`

**Comment by rhusar** [comment]
The FQCN is already `org.jgroups.protocols.kubernetes.KUBE_PING` as configured in the stack, so the protocol name doesn't seem to be the issue here.

**Comment by belaban** [comment]
@rhusar If you look at `org.jgroups.protocols.org.jgroups.protocols.kubernetes.KUBE_PING`, then obviously the absolute classname is constructed incorrectly...

**Comment by rhusar** [comment]
If you read the whole message:

```(either with relative - org.jgroups.protocols.kubernetes.KUBE_PING - or absolute - org.jgroups.protocols.org.jgroups.protocols.kubernetes.KUBE_PING - class name)```

It tried both. Without prefix, then with prefix.

TBH JGroups shouldn't be appending the prefix is the provided protocol name already starts with that prefix...

**Comment by belaban** [comment]
Look at the absolute name, it is incorrect

**Comment by belaban** [comment]
I checked in `master`: absolute protocol names still work! I'll take a quick look at KUBE_PING now...

**Comment by belaban** [comment]
It worked; must be the missing JAR then

**Comment by rhusar** [comment]
Closing – reopen with more information.
