### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

### ISSUE THREAD

**Issue by Huthesh** [jgroups-extras/jgroups-kubernetes#167]
Kube ping throwing following error. 

WARN  2022-09-01 12:34:27,780  [main] org.jgroups.protocols.kubernetes.KUBE_PING: failed getting JSON response from Kubernetes Client[masterUrl=https://10.96.0.1:443/api/v1, headers={Authorization=#MASKED:1031#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@603042a5] for cluster [jgroups-cluster], namespace [], labels [null]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure]]

But we are able to make direct curl call to kubernetes API endpoint. 

* About to connect() to 10.96.0.1 port 443 (#0)
*   Trying 10.96.0.1...
* Connected to 10.96.0.1 (10.96.0.1) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  CApath: none
* NSS: client certificate not found (nickname not specified)
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: ST=Texas,OU=test,O=example,L=Austin,C=US,CN=kubernetes.default
* 	start date: Aug 18 00:21:46 2022 GMT
* 	expire date: Aug 18 00:21:46 2027 GMT
* 	common name: kubernetes.default
* 	issuer: ST=Texas,OU=test,O=example,L=Austin,C=US,CN=K8s CA

What could be the issue here?

**Comment by rhusar** [comment]
@Huthesh Which k8s distro+version is this applicable to? Does this manifest right at the start or after some time?

**Comment by Huthesh** [comment]
issue seems to be  with TLS setting [here](https://github.com/jgroups-extras/jgroups-kubernetes/blob/main/src/main/java/org/jgroups/protocols/kubernetes/stream/TokenStreamProvider.java#L110)

It's working with TLSv1.2.  May be you need to provide a config to set this value instead of hard coding.
