### ISSUE TITLE
How often kube ping calls Kuberentes get pod API

### ISSUE THREAD

**Issue by Huthesh** [jgroups-extras/jgroups-kubernetes#171]
How often kube ping invokes Kubernetes get POD API? Can we configure this frequency?

**Comment by belaban** [comment]
This is called in 2 places: `GMS` runs a discovery on initial startup and `MERGE3` runs it periodically to detect if we have a split brain situation. I assume you refer to the latter. You need to change `min_interval` and `max_interval` in `MERGE3`: the interval will then be a random value within that range.
