### ISSUE TITLE
compatibility with newer versions of jgroups?

### ISSUE THREAD

**Issue by prateekjainaa** [jgroups-extras/jgroups-kubernetes#182]
Hi,

I am trying to use jgroups-kubernetes to manage apache-artemis cluster. Issue that I am facing is, that apache-artemis is using jgroup version 5.2.0.Final. While trying to dig more into it, I fould similar issues were filed earlier for example, [https://github.com/jgroups-extras/jgroups-kubernetes/issues/149](https://github.com/jgroups-extras/jgroups-kubernetes/issues/149) . These were closed mentioning that latest version (1.0.16.Final) only works with jgroups version 4.x. 

I would like to know if there are any plans to update this plugin. 

Regards,
Prateek

**Comment by rhusar** [comment]
Hi @prateekjainaa - the version 1.x of this project is for JGroups 4.x and version 2.0 (main branch) is for usage with JGroups 5.x.

https://github.com/jgroups-extras/jgroups-kubernetes/tree/main
https://github.com/jgroups-extras/jgroups-kubernetes/blob/main/pom.xml#L56

https://github.com/jgroups-extras/jgroups-kubernetes/tree/1.x
https://github.com/jgroups-extras/jgroups-kubernetes/blob/1.x/pom.xml#L56

I am realizing this information is missing in our docs, I will fix that.

**Comment by rhusar** [comment]
Also, I am realizing now that we haven't released 2.x yet on github releases, the latest one is out now:

https://github.com/jgroups-extras/jgroups-kubernetes/releases/tag/2.0.1.Final

**Comment by rhusar** [comment]
@prateekjainaa Well, it was always released in maven - https://central.sonatype.com/artifact/org.jgroups.kubernetes/jgroups-kubernetes/2.0.1.Final - and also an SCM tag - https://github.com/jgroups-extras/jgroups-kubernetes/tree/2.0.1.Final - it's just that for github UI to pick it up, it needs to be explicitly released there too.

**Comment by rhusar** [comment]
OK sounds like we can close this then - opened https://github.com/jgroups-extras/jgroups-kubernetes/issues/183 to add docs on compatibility. Reopen if anything else / open new issue.
