### ISSUE TITLE
WildFly is Unable to Discover Pods on Azure AKS Using KUBE_PING Protocol

### ISSUE THREAD

**Issue by hansakaw** [jgroups-extras/jgroups-kubernetes#190]
**Issue:**
Clustering setup is **not working** as intended with **KUBE_PING protocol** on **Microsoft Azure AKS** on **JDK 8** but works with JDK 11. Seeing below WARN log. Only the current Pod has joined the cluster.

**Excepted:**
All Pods to join the cluster and sessions to be distributed.

**Tools and Versions:**
Kubernetes Version - 1.25.6
JDK - OpenJDK 8
WildFly - 24.0.1

**Log Output:**
`WARN  [org.jgroups.protocols.kubernetes.KUBE_PING] (ServerService Thread Pool -- 90) failed getting JSON response from Kubernetes Client[masterUrl=[https://10.0.0.1:443/api/v1](https://10.0.0.1/api/v1), headers={Authorization=#MASKED:1521#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@74410e13] for cluster [ejb], namespace [demo-hw], labels [clusterType=demo-web-app]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure]]`

Following command only shows the current Pod in the cluster:
`jboss-cli> /subsystem=jgroups/channel=ee:read-attribute(name=view,include-defaults=true)`

JGroups Config in _standalone-full-ha.xml_:
```html
<subsystem xmlns="urn:jboss:domain:jgroups:8.0">
    <channels default="ee">
        <channel cluster="ejb" name="ee" stack="tcp"/>
    </channels>
    <stacks>
        <stack name="udp">
            <transport socket-binding="jgroups-udp" type="UDP"/>
            <protocol type="PING"/>
            <protocol type="MERGE3"/>
            <socket-protocol socket-binding="jgroups-udp-fd" type="FD_SOCK"/>
            <protocol type="FD_ALL"/>
            <protocol type="VERIFY_SUSPECT"/>
            <protocol type="pbcast.NAKACK2"/>
            <protocol type="UNICAST3"/>
            <protocol type="pbcast.STABLE"/>
            <protocol type="pbcast.GMS"/>
            <protocol type="UFC"/>
            <protocol type="MFC"/>
            <protocol type="FRAG3"/>
        </stack>
        <stack name="tcp">
            <transport socket-binding="jgroups-tcp" type="TCP"/>
            <protocol type="kubernetes.KUBE_PING">
                <property name="namespace">${env.POD_NAMESPACE:default}</property>
                <property name="labels">${env.POD_LABEL}</property>
                <property name="dump_requests">true</property>
            </protocol>
            <protocol type="MERGE3"/>
            <protocol type="FD_SOCK"/>
            <protocol type="FD_ALL"/>
            <protocol type="VERIFY_SUSPECT"/>
            <protocol type="pbcast.NAKACK2"/>
            <protocol type="UNICAST3"/>
            <protocol type="pbcast.STABLE"/>
            <protocol type="pbcast.GMS"/>
            <protocol type="MFC"/>
            <protocol type="FRAG2"/>
        </stack>
    </stacks>
</subsystem>
```

**Comment by rhusar** [comment]
I will look into the issue, but be sure to note that JDK 8 "active support" ended on (31 Mar 2022) 1 year and 2 months ago, so upgrading to JDK 11 is the move in the right direction.

**Comment by hansakaw** [comment]
Thanks @rhusar. We got plans to move to a more later version, probably JDK 17. But dates are not confirmed as its not that easy to convince the top level when the JDK 17's Security Support ends before JDK 8.

**Comment by hansakaw** [comment]
**Quick update!**

This seems to be fine after installing **libstdc++** on to the Docker image.
