### ISSUE TITLE
Replace DNR with some descent JSON parser

### ISSUE THREAD

**Issue by slaskawi** [jgroups-extras/jgroups-kubernetes#22]

**Comment by slaskawi** [comment]
How about this: https://github.com/bolerio/mjson/blob/master/src/java/mjson/Json.java ?

**Comment by belaban** [comment]
Excellent choice! Super easy to use; I'll remove jboss-dmr today and use the JSON parser above.

**Comment by belaban** [comment]
Done: jgroups-kubernetes Alpha6

**Comment by belaban** [comment]
@slaskawi If you have a moment, it would be cool for this to get tested running in Openshift!
