### ISSUE TITLE
Memory leak in mjson library

### ISSUE THREAD

**Issue by Macok** [jgroups-extras/jgroups-kubernetes#37]
There is a memory leak just discovered in mjson library, which this project is using.
https://github.com/bolerio/mjson/issues/27

Here's some analysis of a heap dump, dumped from our application using your KubePing implementation.
![leak2](https://user-images.githubusercontent.com/881054/30647713-74ba1630-9e1c-11e7-89a7-ac6f6aaf7b62.PNG)

I would suggest switching to more mature json parser, at least until mjson issue gets fixed.

**Comment by slaskawi** [comment]
Thanks @Macok for noticing. I proposed fix here: https://github.com/bolerio/mjson/pull/28

**Comment by slaskawi** [comment]
Fixed by https://github.com/jgroups-extras/jgroups-kubernetes/pull/38
