### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by SebastianStehle** [jgroups-extras/jgroups-kubernetes#46]
Hi, 

I am getting a 403 in gcloud, when the pod-client tries to query all pods. Have you experienced it?

**Comment by belaban** [comment]
Incorrect permissions? What's the stack trace?

**Comment by SebastianStehle** [comment]
Yes, got it fixed. I was using an older cluster before where the service account had much more permissions before. Therefore I was not aware that you have to give permissions.

**Comment by belaban** [comment]
Alright, glad you fixed it! Can you close this issue then?
