### ISSUE TITLE
How to push a new version to public maven repo?

### ISSUE THREAD

**Issue by uromahn** [jgroups-extras/jgroups-kubernetes#53]
My two PRs have been merged into master with the pom.xml showing the new version 1.0.7. How do I get this now pushed to the public maven repos? Is there something I have to do or someone from the committer team?

Thanks!

**Comment by belaban** [comment]
I updated JGroups to 4.0.12.Final and released jgroups-kubernetes 1.0.7.Final. The new version number is now 1.0.8-SNAPSHOT.
Cheers

**Comment by missedone** [comment]
there's no git tag of 1.0.7, also no 1.0.7.Final artifact available in central maven repo http://search.maven.org/#search%7Cga%7C1%7Cjgroups-kubernetes

**Comment by belaban** [comment]
It's in https://repository.jboss.org/nexus; probably needs syncing with maven central. I don't know what the sync interval is, but wait a few hrs and it should be there

**Comment by missedone** [comment]
OK, i see the jar in central maven repo, however, there's missing git tag in this repo, it's better to add it.
