### ISSUE TITLE
RFE: Use a Service for discovery rather than labels

### ISSUE THREAD

**Issue by brix4dayz** [jgroups-extras/jgroups-kubernetes#54]
Although a Service uses labels for selecting which Pods to forward traffic to, it also considers the liveness and readiness probes to ensure that it only creates Endpoints for Pods which are considered "Ready". Other applications, such as [Apache Ignite ](https://github.com/pires/apache-ignite-discovery-kubernetes) use Services for getting Endpoints to get Pod IPs, rather than label selectors for this reason AFAIK.

With the current implementation, KUBE_PING discovers all Pods in the Running state matching the provided labels and ignores whether they are healthy or not. However, I could see the argument for letting the application using JGroups to determine whether or not a peer is healthy, but this could save it the effort of having to connect and do that check.

The Kubernetes docs themselves recommend [headless Service's](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services) as a means of discovery.

**Comment by belaban** [comment]
Doesn't podRunning() [1] check for pod status?

[1] https://github.com/jgroups-extras/jgroups-kubernetes/blob/master/src/main/java/org/jgroups/protocols/kubernetes/Client.java#L131

**Comment by brix4dayz** [comment]
Yep apologies confused phase for status.

**Comment by belaban** [comment]
I'm always interested in suggestions.. e.g. in the form of a pull request :-)

**Comment by slaskawi** [comment]
@brix4dayz Actually, you can use [DNS_PING](http://www.jgroups.org/manual4/#_dns_ping) which does exactly what you want - it can use Service (DNS entries to be precise) to obtain cluster members IPs.

**Comment by missedone** [comment]
In my experience, KUBE_PING is a more generic solution as sometimes we don't have Service at all.

**Comment by brix4dayz** [comment]
@slaskawi had no idea K8s made SRV records like that, very cool! Thanks, that is more along the lines of what I has thinking.

@missedone though you might not have a Service, you have to create a ServiceAccount and a RoleBinding (at least for OpenShift) in order to use KUBE_PING I think its worth noting. Depending on the policies your cluster admin is enforcing, it might be easier to make a Service.

**Comment by missedone** [comment]
@slaskawi, is there any example about using DNS_PING in kubernetes? thx

**Comment by missedone** [comment]
> you have to create a ServiceAccount and a RoleBinding (at least for OpenShift) in order to use KUBE_PING I think its worth noting. Depending on the policies your cluster admin is enforcing

agreed :)

**Comment by slaskawi** [comment]
@missedone Here's an example project I used for testing: https://github.com/slaskawi/jgroups-dns-ping-example
