### ISSUE TITLE
MJson Memory leak

### ISSUE THREAD

**Issue by SebastianStehle** [jgroups-extras/jgroups-kubernetes#58]
Hi,

we are using your package in a test environment and are facing the following leak:

https://github.com/bolerio/mjson/issues/27

I am not 100% sure if it has been fixed but it brings our system down after a few days. Our small application consumes 2GB of RAM at the moment and 80% is the json leak.

**Comment by belaban** [comment]
It looks as if the fix proposed by @slaskawi is already in the Json class that's part of jgroups-kubernetes?

**Comment by SebastianStehle** [comment]
Sorry, I guess we just have to update the version number :)

**Comment by belaban** [comment]
OK, let me know if this works

**Comment by SebastianStehle** [comment]
So far it looks much better.
