### ISSUE TITLE
Setup CI -- e.g. Travis CI

### ISSUE THREAD

**Issue by rhusar** [jgroups-extras/jgroups-kubernetes#62]

**Comment by slaskawi** [comment]
I can look into that but after my PTO (so after June 10th).

**Comment by rhusar** [comment]
Given that it's still working on Jenkins, lets revisit this once it becomes a problem.

**Comment by slaskawi** [comment]
Ok, I can confirm - Jenkins works as expected - https://github.com/jgroups-extras/jgroups-kubernetes/pull/71
