### ISSUE TITLE
Tags for released version are missing

### ISSUE THREAD

**Issue by rhusar** [jgroups-extras/jgroups-kubernetes#63]
https://repository.jboss.org/nexus/index.html#nexus-search;gav~org.jgroups.kubernetes~jgroups-kubernetes~~~~kw,versionexpand

**Comment by slaskawi** [comment]
Hey @belaban 

I guess you did all the releases. Could you please `git push --tags upstream`, just to push all the tags to the repo?

**Comment by belaban** [comment]
I do see tag `1.10.1.Final`, I did a push when I released it!

**Comment by rhusar** [comment]
I had to already fix this myself as it halted productization process.
