### ISSUE TITLE
kube_ping not discovering members

### ISSUE THREAD

**Issue by pabrahamusa** [jgroups-extras/jgroups-kubernetes#73]
I have configured Kube_Ping , and it seems each 'supposed to be member' is creating separate cluster . But kube_ping is connecting  and resolving all pod ip address. But somehow each pod created it own cluster and causing port conflict when they try to communicate each other.

Kubernetes Client Version: v1.15.0
Kubernetes Server Version: v1.11.10
Cloud: AWS
Jgroups version - 4.1.1.Final

config.xml
`
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="urn:org:jgroups"
        xsi:schemaLocation="urn:org:jgroups http://www.jgroups.org/schema/jgroups.xsd">

    <TCP
            external_addr="${JGROUPS_EXTERNAL_ADDR:match-interface:eth0}"
            bind_addr="match-interface:eth0"
            bind_port="${TCP_PORT:51000}"

            recv_buf_size="5M"
            send_buf_size="1M"
            max_bundle_size="64K"
            enable_diagnostics="true"
            thread_naming_pattern="cl"

            thread_pool.min_threads="0"
            thread_pool.max_threads="500"
            thread_pool.keep_alive_time="30000" />

    <org.jgroups.protocols.kubernetes.KUBE_PING
     port_range="1"
     namespace="${KUBERNETES_NAMESPACE:dev}"
     labels="${KUBERNETES_LABEL:app=mytest}"/>

    <MERGE3 max_interval="30000"
            min_interval="10000"/>
    <FD_SOCK external_addr="${JGROUPS_EXTERNAL_ADDR}"
             start_port="${FD_SOCK_PORT:9000}"/>
    <FD_ALL timeout="30000" interval="5000"/>
    <VERIFY_SUSPECT timeout="1500"  />
    <BARRIER />
    <pbcast.NAKACK2 xmit_interval="500"
                    xmit_table_num_rows="100"
                    xmit_table_msgs_per_row="2000"
                    xmit_table_max_compaction_time="30000"
                    use_mcast_xmit="false"
                    discard_delivered_msgs="true"/>
    <UNICAST3 xmit_interval="500"
              xmit_table_num_rows="100"
              xmit_table_msgs_per_row="2000"
              xmit_table_max_compaction_time="60000"
              conn_expiry_timeout="0"/>
       
    <pbcast.STABLE stability_delay="1000" desired_avg_gossip="50000"
                   max_bytes="4M"/>
    <pbcast.GMS print_local_addr="true" join_timeout="3000"
                view_bundling="true"/>
    <UFC max_credits="2M"
         min_threshold="0.4"/>
    <MFC max_credits="2M"
         min_threshold="0.4"/>
    <FRAG2 frag_size="60K"  />
    <RSVP resend_interval="2000" timeout="10000"/>
    <pbcast.STATE_TRANSFER />
    
</config>
`

Output from Pod - mytest-0
----------------------------------------------------

```javascript
Jul 13, 2019 1:12:55 AM org.jgroups.protocols.BaseBundler sendSingleMessage
mytest-0 mytest SEVERE: JGRP000029: mytest-0-4809: failed sending message to 190.169.144.2:51001 (166 bytes): java.net.ConnectException: Connection refused (Connection refused), headers: KUBE_PING: [GET_MBRS_REQ cluster=mytest-Cluster-dev initial_discovery=false], TP: [cluster=mytest-Cluster-dev]
mytest-0 mytest Jul 13, 2019 1:12:55 AM org.jgroups.protocols.BaseBundler sendSingleMessage
mytest-0 mytest SEVERE: JGRP000029: mytest-0-4809: failed sending message to 190.169.144.12:51001 (166 bytes): java.net.ConnectException: Connection refused (Connection refused), headers: KUBE_PING: [GET_MBRS_REQ cluster=mytest-Cluster-dev initial_discovery=false], TP: [cluster=mytest-Cluster-dev]
```
Output from pod - mytest-1
----------------------------------------------------
 
```javascript
Jul 13, 2019 1:19:11 AM org.jgroups.protocols.BaseBundler sendSingleMessage
mytest-1 mytest SEVERE: JGRP000029: mytest-1-1061: failed sending message to 190.169.144.12:51001 (166 bytes): java.net.ConnectException: Connection refused (Connection refused), headers: KUBE_PING: [GET_MBRS_REQ cluster=mytest-Cluster-dev initial_discovery=false], TP: [cluster=mytest-Cluster-dev]
mytest-1 mytest Jul 13, 2019 1:19:11 AM org.jgroups.protocols.BaseBundler sendSingleMessage
mytest-1 mytest SEVERE: JGRP000029: mytest-1-1061: failed sending message to 190.169.144.2:51001 (166 bytes): java.net.ConnectException: Connection refused (Connection refused), headers: KUBE_PING: [GET_MBRS_REQ cluster=mytest-Cluster-dev initial_discovery=false], TP: [cluster=mytest-Cluster-dev]
```

**Comment by slaskawi** [comment]
> I have configured Kube_Ping , and it seems each 'supposed to be member' is creating separate cluster . But kube_ping is connecting and resolving all pod ip address. But somehow each pod created it own cluster and causing port conflict when they try to communicate each other.

This is a typical symptom, that discovery doesn't work. 

From the logs I can clearly see that something is blocking communication on port `51001`. Could you please try to remove `port_range="1"` and let KUBE_PING figure out the best port for itself?

**Comment by pabrahamusa** [comment]
Thanks slaskawi ,

I removed the port_range="1" and kube_ping was still probing 51001 so I put port_range="0" and the error disappeared. Not sure that means it is working.
I am running two pods,  both says  no members discovered and creating cluster as first member. Is this a normal behaviour?. However the logs correctly displaying the pods from api server on both containers.

pod - mytest-0
----------------
ul 16, 2019 1:09:30 AM org.jgroups.protocols.pbcast.ClientGmsImpl joinInternal
INFO: mytest-0-64343: no members discovered after 3246 ms: creating cluster as first member
Tue Jul 16 01:09:30 UTC 2019   Info: main File logging turned on:  /dev/stdout

pod - mytest-1
----------------
Jul 16, 2019 1:10:10 AM org.jgroups.protocols.pbcast.ClientGmsImpl joinInternal
INFO: mytest-1-57027: no members discovered after 3323 ms: creating cluster as first member
Tue Jul 16 01:10:10 UTC 2019   Info: main File logging turned on:  /dev/stdout

**Comment by slaskawi** [comment]
> I removed the port_range="1" and kube_ping was still probing 51001 so I put port_range="0" and the error disappeared. Not sure that means it is working.

This is absolutely fine. All it means, is that JGroups were able to form a cluster by communicating through port `51000`. Port `51001` was blocked (probably through a firewall or some iptables settings).

> I am running two pods, both says no members discovered and creating cluster as first member. Is this a normal behaviour?. However the logs correctly displaying the pods from api server on both containers.

Could you please send me full logs? It would be perfect, if the logs were on `DEBUG` level. I'm specifically looking what `views` were emitted by JGroups.

In general, it sounds like you have strict firewall rules in your setup. Pods are able to communicate with each other only on a very specific ports. It might be helpful if you told me some more details about this...

**Comment by pabrahamusa** [comment]
Hi slaskawi ,
Thanks again for looking into this. I have tested this and can see it is working.  These are the logs . Thanks for your help..!


-----------------------
POD mytest-0
-----------------------
mytest-0 mytest
mytest-0 mytest Fri Jul 19 01:36:25 UTC 2019   Info: main App:  Creating jgroups mytest manager cluster: mytestManager-Cluster-dev
mytest-0 mytest  STARTING JCHANNEL from ./conf/mytestserver_jgroups2.xml
mytest-0 mytest Jul 19, 2019 1:36:28 AM org.jgroups.stack.Configurator resolveAndAssignField
mytest-0 mytest WARNING: JGRP000014: GMS.view_bundling has been deprecated: view bundling is enabled by default
mytest-0 mytest Jul 19, 2019 1:36:28 AM org.jgroups.protocols.kubernetes.KUBE_PING init
mytest-0 mytest INFO: namespace dev set; clustering enabled
mytest-0 mytest  @Connecting to  JCHANNEL from mytestManager-Cluster-dev
mytest-0 mytest
mytest-0 mytest -------------------------------------------------------------------
mytest-0 mytest GMS: address=mytest-0-1705, cluster=mytestManager-Cluster-dev, physical address=190.169.144.25:51000
mytest-0 mytest -------------------------------------------------------------------
mytest-0 mytest --> https://100.120.0.1:443/api/v1/namespaces/dev/pods?labelSelector=app%3Dmytest

 19, 2019 1:36:31 AM org.jgroups.protocols.pbcast.ClientGmsImpl joinInternal
mytest-0 mytest INFO: mytest-0-1705: no members discovered after 3272 ms: creating cluster as first member
mytest-0 mytest  Connected to  JCHANNEL from mytestManager-Cluster-dev
mytest-0 mytest  Completed INIT OF  JCHANNEL
mytest-0 mytest Fri Jul 19 01:36:31 UTC 2019   Info: main File logging turned on:  /dev/stdout
mytest-0 mytest /dev/stdout activated
mytest-0 mytest Fri Jul 19 01:36:31 UTC 2019   Info: main App:  Client Server started on port:  19654
mytest-0 mytest Fri Jul 19 01:36:31 UTC 2019   Info: main Control Server started on port:19655
mytest-0 mytest Fri Jul 19 01:36:31 UTC 2019   Warning: StatusMonitor mytest Status Logger started ...
mytest-0 mytest Fri Jul 19 01:36:31 UTC 2019   Warning: StatusMonitor mytest Status Logger polling ...
mytest-0 mytest Fri Jul 19 01:36:31 UTC 2019   Warning: StatusMonitor <----> Data Collection Id:




---------------------------
POD mytest-1
---------------------------
mytestmanager-1 mytest Fri Jul 19 01:36:56 UTC 2019   Info: main App:  Creating jgroups mytest manager cluster: mytestManager-Cluster-dev
mytest-1 mytest  STARTING JCHANNEL from ./conf/mytestserver_jgroups2.xml
mytest-1 mytest Jul 19, 2019 1:37:03 AM org.jgroups.stack.Configurator resolveAndAssignField
mytest-1 mytest WARNING: JGRP000014: GMS.view_bundling has been deprecated: view bundling is enabled by default
mytest-1 mytest Jul 19, 2019 1:37:03 AM org.jgroups.protocols.kubernetes.KUBE_PING init
mytest-1 mytest INFO: namespace dev set; clustering enabled
mytest-1 mytest  Connecting to  JCHANNEL from mytestManager-Cluster-dev
mytest-1 mytest
mytest-1 mytest -------------------------------------------------------------------
mytest-1 mytest GMS: address=mytest-1-24010, cluster=mytestManager-Cluster-dev, physical address=190.169.128.3:51000
mytest-1 mytest -------------------------------------------------------------------
mytest-1 mytest --> https://100.120.0.1:443/api/v1/namespaces/dev/pods?labelSelector=app%3Dmytest

mytest-1 mytest
mytest-1 mytest  Connected to  JCHANNEL from mytestManager-Cluster-dev
mytest-1 mytest  Completed INIT OF  JCHANNEL
mytest-1 mytest Fri Jul 19 01:37:03 UTC 2019   Info: main File logging turned on:  /dev/stdout
mytest-1 mytest /dev/stdout activated
mytest-1 mytest Fri Jul 19 01:37:03 UTC 2019   Info: main App:  Client Server started on port:  19654
mytest-1 mytest Fri Jul 19 01:37:03 UTC 2019   Info: main Control Server started on port:19655
mytest-1 mytest Fri Jul 19 01:37:03 UTC 2019   Warning: StatusMonitor mytest Status Logger started ...
mytest-1 mytest Fri Jul 19 01:37:03 UTC 2019   Warning: StatusMonitor mytest Status Logger polling ...
mytest-1 mytest Fri Jul 19 01:37:03 UTC 2019   Warning: StatusMonitor <----> Data Collection Id:

**Comment by slaskawi** [comment]
Even though I don't see any `view` changes in your application, I believe you got this working, right? 

Just in case:

- If you're using a Wildfly-based application (like Infinispan or Keycloak for example) you should see something like this in the logs:
```
07:24:27,497 INFO  [org.infinispan.CLUSTER] (thread-9,ejb,606d26e8608a) ISPN000094: Received new cluster view for channel ejb: [606d26e8608a|1] (2) [606d26e8608a, 8517d9d0af65]
```

- If you're using only JGroups, you might grab a view using this code snippet:

```java
channel=new JChannel(props);
channel.setReceiver(new ReceiverAdapter() {
    public void viewAccepted(View view) {
        System.out.println(view);        
    }
});
channel.connect(channel_name);
```

**Comment by pabrahamusa** [comment]
Hi slaskawi ,

it is working and I added the code as you provided. The views are displayed on both pods. The second pod got one additional view as well. I assume that is expected?

mytest-0 mytest The view is == [mytest-0-29425|0] (1) [mytest-0-29425]
mytest-1 mytest The view is == [mytest-0-29425|1] (2) [mytest-0-29425, mytest-1-4456]

**Logs:-**

**pod - mytest-0**

anager-0 mytest Fri Jul 19 22:34:59 UTC 2019   Info: main App:  Creating jgroups mytest manager cluster: mytestManager-Cluster-dev
mytest-0 mytest  STARTING JCHANNEL from ./conf/mytestserver_jgroups2.xml
mytest-0 mytest Jul 19, 2019 10:35:05 PM org.jgroups.stack.Configurator resolveAndAssignField
mytest-0 mytest WARNING: JGRP000014: GMS.view_bundling has been deprecated: view bundling is enabled by default
mytest-0 mytest Jul 19, 2019 10:35:05 PM org.jgroups.protocols.kubernetes.KUBE_PING init
mytest-0 mytest INFO: namespace dev set; clustering enabled
mytest-0 mytest  Connecting to  JCHANNEL from mytestManager-Cluster-dev
mytest-0 mytest
mytest-0 mytest -------------------------------------------------------------------
mytest-0 mytest GMS: address=mytest-0-29425, cluster=mytestManager-Cluster-dev, physical address=190.169.128.3:51000
mytest-0 mytest -------------------------------------------------------------------
mytest-0 mytest --> https://100.120.0.1:443/api/v1/namespaces/dev/pods?labelSelector=app%3Dmytest

mytest-0 mytest Jul 19, 2019 10:35:09 PM org.jgroups.protocols.pbcast.ClientGmsImpl joinInternal
mytest-0 mytest INFO: mytest-0-29425: no members discovered after 3277 ms: creating cluster as first member
mytest-0 mytest The view is == [mytest-0-29425|0] (1) [mytest-0-29425]
mytest-0 mytest  Connected to  JCHANNEL from mytestManager-Cluster-dev
mytest-0 mytest  Completed INIT OF  JCHANNEL





**pod - mytest-1** 

mytest-1 mytest Fri Jul 19 22:35:32 UTC 2019   Info: main Java mytest Manager->processArgs
mytest-1 mytest
mytest-1 mytest Fri Jul 19 22:35:32 UTC 2019   Info: main App:  Creating jgroups mytest manager cluster: mytestManager-Cluster-dev
mytest-1 mytest  STARTING JCHANNEL from ./conf/mytestserver_jgroups2.xml
mytest-1 mytest Jul 19, 2019 10:35:34 PM org.jgroups.stack.Configurator resolveAndAssignField
mytest-1 mytest WARNING: JGRP000014: GMS.view_bundling has been deprecated: view bundling is enabled by default
mytest-1 mytest Jul 19, 2019 10:35:34 PM org.jgroups.protocols.kubernetes.KUBE_PING init
mytest-1 mytest INFO: namespace dev set; clustering enabled
mytest-1 mytest  Connecting to  JCHANNEL from mytestManager-Cluster-dev
mytest-1 mytest
mytest-1 mytest -------------------------------------------------------------------
mytest-1 mytest GMS: address=mytest-1-4456, cluster=mytestManager-Cluster-dev, physical address=190.169.144.25:51000
mytest-1 mytest -------------------------------------------------------------------
mytest-1 mytest --> https://100.120.0.1:443/api/v1/namespaces/dev/pods?labelSelector=app%3Dmytest

mytest-1 mytest The view is == [mytest-0-29425|1] (2) [mytest-0-29425, mytest-1-4456]
mytest-1 mytest  Connected to  JCHANNEL from mytestManager-Cluster-dev
mytest-1 mytest  Completed INIT OF  JCHANNEL
mytest-1 mytest Fri Jul 19 22:35:34 UTC 2019   Info: main File logging turned on:  /dev/stdout
mytest-1 mytest /dev/stdout activated

**Comment by slaskawi** [comment]
Thanks a lot for the logs @pabrahamusa 

Yes, you can increase the sleep time, See https://github.com/jgroups-extras/jgroups-kubernetes#kube_ping-configuration
