### ISSUE TITLE
KUBE_PING warning with StatefulSet

### ISSUE THREAD

**Issue by jmesnil** [jgroups-extras/jgroups-kubernetes#75]
The [WildFly Operator](/wildfly/wildlfy-operator) is using a `StatefulSet` to deploy application on Kubernetes/OpenShift.

It was possible to use KUBE_PING with WildFly 17 (and the JGroups version that it integrated) but there is a new warning with WildFly 18 during the deployment of the application:

```
08:46:20,187 WARN  [org.jgroups.protocols.kubernetes.KUBE_PING] (thread-17,ejb,clusterbench-1) metadata.labels.pod-template-hash not found in pod json. Impossible to reliably determine pod group during Rolling Update
```

Indeed pod-template-hash label is set only for pods coming from a `Deployment`[1] and is not present when a `StatefulSet` is used.

Is this warning by design or should KUBE_PING work with StatefulSets without any issue?

[1] https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#pod-template-hash-label

**Comment by jmesnil** [comment]
WildFly 18 uses jgroups-kubernetes 1.0.12.Final
WildFly 17 uses jgroups-kubernetes 1.0.9.Final

**Comment by rhusar** [comment]
I am not sure, are you just seeing a warning or does the discovery not work?

The change that introduced this is https://github.com/jgroups-extras/jgroups-kubernetes/commit/be3d7339411c2c7a3136c3230b0f193589cb0964

**Comment by jmesnil** [comment]
@rhusar I edit the issue, I thought it was not working but I was not patient enough for the cluster to be formed :)

So, it's working but it logs this warning

**Comment by slaskawi** [comment]
@jmesnil @rhusar The clustering should work fine, however, you won't be able to separate deployments during rolling update (see `split_clusters_during_rolling_update` property). I believe we'll need to enhance this feature to support `StatefulSets` as well.

**Comment by rhusar** [comment]
The WF Jira for this is https://issues.jboss.org/browse/WFLY-12657.
