### ISSUE TITLE
Labels system property name inconsistence

### ISSUE THREAD

**Issue by mshaposhnik** [jgroups-extras/jgroups-kubernetes#79]
As far as i can see in code, labels filtering property name is
`KUBERNETES_LABELS`
(https://github.com/jgroups-extras/jgroups-kubernetes/blob/master/src/main/java/org/jgroups/protocols/kubernetes/KUBE_PING.java#L81)
But in readme, it is 2 times mentioned as `KUBERNETES_LABEL`. 

is that a bug or am I missing something? I can prepare readme fixup PR if you wish.

**Comment by slaskawi** [comment]
Thanks for spotting this @mshaposhnik !

Yes, it would be great if you could prepare a Pull Request with a fix. Please remember about backwards compatibility (even though it was an obvious typo, old deployments should work with it) and documentation update.

**Comment by belaban** [comment]
I fixed this in the readme, thx,
